### ISSUE TITLE
Enhancement Request:  Syntax for more "random data" fields beyond required fields

### ISSUE THREAD

**Issue by kghu** [benahm/TDF#1]
This is a very helpful, easy-to-use helper class.

One thing that could make it more useful is an ability to specify fields you'd like the helper class to invent data for.

The helper class is already inventing data for any "required" fields it comes across.

If there were a syntax to specify other fields for which it'd be desirable for it to make up completely random data, it would be even more useful.

**Comment by benahm** [comment]
Hi, 

Thanks for reporting this need
 
I added this feature in the latest [version ](https://github.com/benahm/TDF/releases/tag/V1.2) 

Now you can specify `TDF.DEFAULT_VALUE`  as a value of a non required field,

The class will automatically auto-generate a value for it

_Example_ :

  ```apex
  Contact con = (Contact)TDF.createSObject('Contact', new Map<String,Object>{
    'Description' => TDF.DEFAULT_VALUE,
    'Email' => TDF.DEFAULT_VALUE
  });
  ```

this will create the following instance of contact

  ```apex
  Contact:{ 
    LastName : 'test0', 
    Description:'test0', 
    Email:'test0@email.com' 
  } 
  ```

**For advanced use** 

You can adapt the auto-generated data for your need by extending the `ADefaultValueProvider `Class
  ```apex
  public class YourDefaultValueProvider extends TDF.ADefaultValueProvider{
  ....
     public override String getEmailDefaultValue(Schema.DescribeSObjectResult objectDesc, Schema.DescribeFieldResult fieldDesc, Integer counter){
      return 'your.custom.test.email'+counter.format()+'@gmail.com';
    }
  ...
  }
  ```

Then you can apply your custom default value provider to the TDF before using it 

  ```apex
  TDF.setDefaultValueProvider(new YourDefaultValueProvider())
  ```

....
