### ISSUE TITLE
Cannot create/insert Account record

### ISSUE THREAD

**Issue by antnoley** [benahm/TDF#4]
The following code compiles, but fails to run when called upon by test methods:
Account acct = (Account)TDF.createSObject('Account',true);

**Comment by benahm** [comment]
Hello @antnoley 

Could you post the exact error shown in the logs,

Make sure that you set `PERSON_ACCOUNT_IS_ENABLED` depending if your org has Person Account enabled or not

In the TDF class 

`private static final Boolean PERSON_ACCOUNT_IS_ENABLED = true | false;`

Thank you

**Comment by antnoley** [comment]
Hi @benahm ,
I don't have Person Account enabled in my org. I'm no longer getting the error, and I'm not exactly sure why. Closing this issue.
