### ISSUE TITLE
Potential Example Issue?

### ISSUE THREAD

**Issue by kbuckles-sfdc** [benahm/TDF#7]
Bear with me, as I am just breaking into development...

But, in the example "Create 10 Cases related to 10 Accounts" it errors our when you use `AccountId` in the Case list. You have to use `Account` or else you get the error:

`The field "accountidid" does not exist on "Case" or the value type provided is incorrect Original error message : Invalid field accountidid for Case`.

I also attached a screen grab:

<img width="719" alt="dev-console-log-20190920" src="https://user-images.githubusercontent.com/48032760/65363725-4a685280-dbc2-11e9-8e15-2cfbdfa7b708.png">

Also - FWIW - This was in a brand new vanilla dev org.

Just wanted to let you know so you can update the examples in the docs.

Thanks! Love it so far!

**Comment by benahm** [comment]
Hello @kbuckles-sfdc 

Thank you for reporting this issue 

You right, there was an issue in the example

When the input is an sObject list we use the relationship name (in this case "Account" not AccountId")

  ```apex
  List<Account> accList = TDF.createSObjectList('Account', new Map<String,Object>{
    'Description' => 'Account Description'
  },10);
  ```
  
  ```apex
  List<Case> caseList = TDF.createSObjectList('Case', new Map<String,Object>{
    'Account' => AccList,
    'Contact.Account' => AccList
  },10);
  ```

Best regards
benahm
